// Code generated by "stringer -type=Opcode,AugOp,BuiltinOp"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Num-1]
	_ = x[Str-2]
	_ = x[Dupe-3]
	_ = x[Drop-4]
	_ = x[Swap-5]
	_ = x[Rote-6]
	_ = x[Field-7]
	_ = x[FieldInt-8]
	_ = x[FieldByName-9]
	_ = x[FieldByNameStr-10]
	_ = x[Global-11]
	_ = x[Local-12]
	_ = x[Special-13]
	_ = x[ArrayGlobal-14]
	_ = x[ArrayLocal-15]
	_ = x[InGlobal-16]
	_ = x[InLocal-17]
	_ = x[AssignField-18]
	_ = x[AssignFieldSub-19]
	_ = x[AssignGlobal-20]
	_ = x[AssignLocal-21]
	_ = x[AssignSpecial-22]
	_ = x[AssignArrayGlobal-23]
	_ = x[AssignArrayLocal-24]
	_ = x[Delete-25]
	_ = x[DeleteAll-26]
	_ = x[IncrField-27]
	_ = x[IncrGlobal-28]
	_ = x[IncrLocal-29]
	_ = x[IncrSpecial-30]
	_ = x[IncrArrayGlobal-31]
	_ = x[IncrArrayLocal-32]
	_ = x[AugAssignField-33]
	_ = x[AugAssignGlobal-34]
	_ = x[AugAssignLocal-35]
	_ = x[AugAssignSpecial-36]
	_ = x[AugAssignArrayGlobal-37]
	_ = x[AugAssignArrayLocal-38]
	_ = x[Regex-39]
	_ = x[IndexMulti-40]
	_ = x[ConcatMulti-41]
	_ = x[Add-42]
	_ = x[Subtract-43]
	_ = x[Multiply-44]
	_ = x[Divide-45]
	_ = x[Power-46]
	_ = x[Modulo-47]
	_ = x[Equals-48]
	_ = x[NotEquals-49]
	_ = x[Less-50]
	_ = x[Greater-51]
	_ = x[LessOrEqual-52]
	_ = x[GreaterOrEqual-53]
	_ = x[Concat-54]
	_ = x[BitAnd-55]
	_ = x[BitOr-56]
	_ = x[Match-57]
	_ = x[NotMatch-58]
	_ = x[Not-59]
	_ = x[UnaryMinus-60]
	_ = x[UnaryPlus-61]
	_ = x[Boolean-62]
	_ = x[Jump-63]
	_ = x[JumpFalse-64]
	_ = x[JumpTrue-65]
	_ = x[JumpEquals-66]
	_ = x[JumpNotEquals-67]
	_ = x[JumpLess-68]
	_ = x[JumpGreater-69]
	_ = x[JumpLessOrEqual-70]
	_ = x[JumpGreaterOrEqual-71]
	_ = x[Next-72]
	_ = x[Nextfile-73]
	_ = x[Exit-74]
	_ = x[ExitStatus-75]
	_ = x[ForIn-76]
	_ = x[BreakForIn-77]
	_ = x[CallBuiltin-78]
	_ = x[CallLengthArray-79]
	_ = x[CallSplit-80]
	_ = x[CallSplitSep-81]
	_ = x[CallSprintf-82]
	_ = x[CallUser-83]
	_ = x[CallNative-84]
	_ = x[Return-85]
	_ = x[ReturnNull-86]
	_ = x[Nulls-87]
	_ = x[Print-88]
	_ = x[Printf-89]
	_ = x[Getline-90]
	_ = x[GetlineField-91]
	_ = x[GetlineGlobal-92]
	_ = x[GetlineLocal-93]
	_ = x[GetlineSpecial-94]
	_ = x[GetlineArray-95]
	_ = x[EndOpcode-96]
}

const _Opcode_name = "NopNumStrDupeDropSwapRoteFieldFieldIntFieldByNameFieldByNameStrGlobalLocalSpecialArrayGlobalArrayLocalInGlobalInLocalAssignFieldAssignFieldSubAssignGlobalAssignLocalAssignSpecialAssignArrayGlobalAssignArrayLocalDeleteDeleteAllIncrFieldIncrGlobalIncrLocalIncrSpecialIncrArrayGlobalIncrArrayLocalAugAssignFieldAugAssignGlobalAugAssignLocalAugAssignSpecialAugAssignArrayGlobalAugAssignArrayLocalRegexIndexMultiConcatMultiAddSubtractMultiplyDividePowerModuloEqualsNotEqualsLessGreaterLessOrEqualGreaterOrEqualConcatBitAndBitOrMatchNotMatchNotUnaryMinusUnaryPlusBooleanJumpJumpFalseJumpTrueJumpEqualsJumpNotEqualsJumpLessJumpGreaterJumpLessOrEqualJumpGreaterOrEqualNextNextfileExitExitStatusForInBreakForInCallBuiltinCallLengthArrayCallSplitCallSplitSepCallSprintfCallUserCallNativeReturnReturnNullNullsPrintPrintfGetlineGetlineFieldGetlineGlobalGetlineLocalGetlineSpecialGetlineArrayEndOpcode"

var _Opcode_index = [...]uint16{0, 3, 6, 9, 13, 17, 21, 25, 30, 38, 49, 63, 69, 74, 81, 92, 102, 110, 117, 128, 142, 154, 165, 178, 195, 211, 217, 226, 235, 245, 254, 265, 280, 294, 308, 323, 337, 353, 373, 392, 397, 407, 418, 421, 429, 437, 443, 448, 454, 460, 469, 473, 480, 491, 505, 511, 517, 522, 527, 535, 538, 548, 557, 564, 568, 577, 585, 595, 608, 616, 627, 642, 660, 664, 672, 676, 686, 691, 701, 712, 727, 736, 748, 759, 767, 777, 783, 793, 798, 803, 809, 816, 828, 841, 853, 867, 879, 888}

func (i Opcode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Opcode_index)-1 {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[idx]:_Opcode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AugOpAdd-0]
	_ = x[AugOpSub-1]
	_ = x[AugOpMul-2]
	_ = x[AugOpDiv-3]
	_ = x[AugOpPow-4]
	_ = x[AugOpMod-5]
}

const _AugOp_name = "AugOpAddAugOpSubAugOpMulAugOpDivAugOpPowAugOpMod"

var _AugOp_index = [...]uint8{0, 8, 16, 24, 32, 40, 48}

func (i AugOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AugOp_index)-1 {
		return "AugOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AugOp_name[_AugOp_index[idx]:_AugOp_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuiltinAtan2-0]
	_ = x[BuiltinClose-1]
	_ = x[BuiltinCos-2]
	_ = x[BuiltinExp-3]
	_ = x[BuiltinFflush-4]
	_ = x[BuiltinFflushAll-5]
	_ = x[BuiltinGsub-6]
	_ = x[BuiltinIndex-7]
	_ = x[BuiltinInt-8]
	_ = x[BuiltinLength-9]
	_ = x[BuiltinLengthArg-10]
	_ = x[BuiltinLog-11]
	_ = x[BuiltinMatch-12]
	_ = x[BuiltinRand-13]
	_ = x[BuiltinSin-14]
	_ = x[BuiltinSqrt-15]
	_ = x[BuiltinSrand-16]
	_ = x[BuiltinSrandSeed-17]
	_ = x[BuiltinSub-18]
	_ = x[BuiltinSubstr-19]
	_ = x[BuiltinSubstrLength-20]
	_ = x[BuiltinSystem-21]
	_ = x[BuiltinTolower-22]
	_ = x[BuiltinToupper-23]
}

const _BuiltinOp_name = "BuiltinAtan2BuiltinCloseBuiltinCosBuiltinExpBuiltinFflushBuiltinFflushAllBuiltinGsubBuiltinIndexBuiltinIntBuiltinLengthBuiltinLengthArgBuiltinLogBuiltinMatchBuiltinRandBuiltinSinBuiltinSqrtBuiltinSrandBuiltinSrandSeedBuiltinSubBuiltinSubstrBuiltinSubstrLengthBuiltinSystemBuiltinTolowerBuiltinToupper"

var _BuiltinOp_index = [...]uint16{0, 12, 24, 34, 44, 57, 73, 84, 96, 106, 119, 135, 145, 157, 168, 178, 189, 201, 217, 227, 240, 259, 272, 286, 300}

func (i BuiltinOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BuiltinOp_index)-1 {
		return "BuiltinOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuiltinOp_name[_BuiltinOp_index[idx]:_BuiltinOp_index[idx+1]]
}
